from pathlib import Path

bridge = Path('android/app/src/main/python/mobile_bridge.py')
text = bridge.read_text(encoding='utf-8')
if 'def run_priority_live_backtest(' not in text:
    anchor = '\ndef run_backtest(\n'
    if anchor not in text:
        raise SystemExit('mobile_bridge run_backtest anchor missing')
    wrapper = '''\ndef run_priority_live_backtest(\n    symbol: str,\n    start_text: str,\n    end_text: str,\n    output_dir: str,\n    database_path: str,\n    initial_capital: float = 1000.0,\n    compounding_enabled: bool = True,\n) -> str:\n    from universal_bot.priority_backtest import run_priority_backtest\n    logs = [\n        "LIVE 통합 Priority 백테스트 시작",\n        "5분 9.55배 + 15분 5배 · 단일 포지션 · 5분 우선",\n        "신호봉 확정 종가 · 고정 TP/SL · 동봉 SL 우선 · 수수료 0.02% + 슬리피지 0.01%/side",\n    ]\n    result = run_priority_backtest(\n        database_path=database_path, start=start_text, end=end_text,\n        initial_capital=float(initial_capital), compounding=bool(compounding_enabled), symbol=symbol,\n    )\n    history_dir = Path(output_dir) / "BacktestResults"\n    history_dir.mkdir(parents=True, exist_ok=True)\n    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")\n    archive = history_dir / f"{stamp}-btc-usdt-priority-live-parity.json"\n    payload = dict(result)\n    payload.update({"database": str(database_path), "requested_start": start_text, "requested_end": end_text,\n                    "selected_database": True, "result_path": str(archive),\n                    "optimization_pipeline": {"stage": "priority_live_parity", "paper_live_applied": False}})\n    archive.write_text(json.dumps(payload, ensure_ascii=False, indent=2, allow_nan=False) + "\\n", encoding="utf-8")\n    logs.append(f"통합 백테스트 완료 · 거래 {int(payload.get('trades') or 0)} · 수익률 {float(payload.get('return_percent') or 0):.2f}% · MDD {float(payload.get('max_drawdown_percent') or 0):.2f}%")\n    return json.dumps({"db": str(database_path), "result": str(archive), "summary": payload, "logs": logs}, ensure_ascii=False)\n\n'''
    text = text.replace(anchor, wrapper + 'def run_backtest(\n', 1)
    bridge.write_text(text, encoding='utf-8')

service = Path('android/app/src/main/java/com/nictunz/universalbacktester/BacktestForegroundService.java')
text = service.read_text(encoding='utf-8')
if 'run_priority_live_backtest' not in text:
    old = '''            } else {\n                response = bridge.callAttr(\n                    "run_backtest",'''
    new = '''            } else if (request.optBoolean("priority_live_parity", false)) {\n                updateNotification("LIVE 5분+15분 통합 백테스트 실행 중");\n                response = bridge.callAttr(\n                    "run_priority_live_backtest",\n                    request.getString("symbol"), request.getString("start"), request.getString("end"),\n                    request.getString("output_dir"), request.optString("database_path", ""),\n                    request.optDouble("initial_capital", 1000.0), request.optBoolean("compounding_enabled", true)\n                ).toString();\n            } else {\n                response = bridge.callAttr(\n                    "run_backtest",'''
    if old not in text:
        raise SystemExit('service dispatch anchor missing')
    text = text.replace(old, new, 1)
    old = '        request.put("database_path", intent.getStringExtra("database_path"));\n'
    if old not in text:
        raise SystemExit('service request anchor missing')
    text = text.replace(old, old + '        request.put("priority_live_parity", intent.getBooleanExtra("priority_live_parity", false));\n', 1)
    service.write_text(text, encoding='utf-8')

main = Path('android/app/src/main/java/com/nictunz/universalbacktester/MainActivity.java')
text = main.read_text(encoding='utf-8')
if 'startPriorityLiveParityBacktest()' not in text:
    old = '''        Button priorityPreset = actionButton("🟢 실거래 동등 프로필 · 5분 / 15분", SUCCESS);\n        priorityPreset.setOnClickListener(v -> new AlertDialog.Builder(this)\n                .setTitle("현재 LIVE 동등 프로필")\n                .setItems(new String[]{"BTC 5분 · 9.55배 · 신호봉 확정 즉시", "BTC 15분 · 5배 · 신호봉 확정 즉시"},\n                        (dialog, which) -> loadPriorityPreset(which == 0 ? "5m" : "15m"))\n                .setNegativeButton("취소", null).show());\n        backtestCard.addView(priorityPreset, marginTop(12));\n        backtestCard.addView(text("LIVE 동등 기준: 신호봉 확정 종가 진입(signal_close) · 편도 수수료 0.02% + 슬리피지 0.01% · 최대 진입 1회 · TP/SL은 최초 진입가 기준 고정. 데이터가 정상일 때 서버는 별도 대기 없이 주문합니다. 5분/15분 우선 전환 조합 성과는 단일 프로필 결과와 구분합니다.",\n                12, MUTED, false), marginTop(6));'''
    new = '''        Button priorityPreset = actionButton("🟢 LIVE 통합 백테스트 · 5분 9.55배 + 15분 5배", SUCCESS);\n        priorityPreset.setOnClickListener(v -> startPriorityLiveParityBacktest());\n        backtestCard.addView(priorityPreset, marginTop(12));\n        backtestCard.addView(text("두 전략을 따로 계산하지 않습니다. 실제 Priority Runtime처럼 하나의 포지션을 공유하고 5분 신호가 15분보다 우선하며, 15분 보유 중 5분 신호가 오면 15분을 정리한 뒤 5분으로 전환합니다. 신호봉 확정 종가 · 고정 TP/SL · 동봉 SL 우선 · 편도 수수료 0.02% + 슬리피지 0.01%.",\n                12, MUTED, false), marginTop(6));'''
    if old not in text:
        raise SystemExit('MainActivity priority button anchor missing')
    text = text.replace(old, new, 1)
    anchor = '    private void startBacktest(JSONObject fixedParameters) {\n'
    if anchor not in text:
        raise SystemExit('MainActivity startBacktest anchor missing')
    method = '''    private void startPriorityLiveParityBacktest() {\n        String symbol = symbolInput.getText().toString().trim();\n        if (!"BTC/USDT:USDT".equalsIgnoreCase(symbol)) { toast("LIVE 통합 프로필은 BTC/USDT:USDT 전용입니다."); return; }\n        if (selectedDbPath == null || selectedDbPath.trim().isEmpty()) { toast("먼저 5분·15분 및 4거래소 데이터가 들어있는 저장 DB를 선택하세요."); return; }\n        String start = startInput.getText().toString().trim();\n        String end = endInput.getText().toString().trim();\n        Calendar startCal = parseDate(start);\n        Calendar endCal = parseDate(end);\n        if (startCal == null || endCal == null || endCal.before(startCal)) { toast("백테스트 시작일과 종료일을 확인하세요."); return; }\n        double initialCapital;\n        try { initialCapital = Double.parseDouble(initialCapitalInput.getText().toString().trim().replace(",", "")); }\n        catch (Exception ignored) { toast("초기자산을 숫자로 입력하세요."); return; }\n        boolean compounding = !"고정식".equals(sizingModeInput.getText().toString().trim());\n        new AlertDialog.Builder(this)\n                .setTitle("LIVE 통합 Priority 백테스트")\n                .setMessage("5분 9.55배 + 15분 5배를 한 계좌/한 포지션으로 시간순 재생합니다.\\n\\n• 5분 신호 우선\\n• 5분 보유 중 신규 신호 차단\\n• 15분 보유 중 5분 신호 → 15분 정리 후 5분 진입\\n• 고정 TP/SL · 동봉 SL 우선\\n• 수수료 0.02% + 슬리피지 0.01% / side")\n                .setPositiveButton("통합 백테스트 실행", (dialog, which) -> {\n                    Intent intent = new Intent(this, BacktestForegroundService.class);\n                    intent.setAction(BacktestForegroundService.ACTION_START);\n                    intent.putExtra("symbol", "BTC/USDT:USDT"); intent.putExtra("timeframe", "5m+15m");\n                    intent.putExtra("start", start); intent.putExtra("end", end); intent.putExtra("database_path", selectedDbPath);\n                    intent.putExtra("initial_capital", initialCapital); intent.putExtra("compounding_enabled", compounding);\n                    intent.putExtra("priority_live_parity", true);\n                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) startForegroundService(intent); else startService(intent);\n                    lastDbPath = ""; lastResultPath = ""; lastUploadEligible = false; lastSummary = null;\n                    enableUpload(false); enableResultActions(false);\n                    setFullLog("LIVE 통합 Priority 백테스트 시작\\n5분 9.55배 + 15분 5배 · 단일 포지션 · 5분 우선\\n");\n                    setBusy(true, "LIVE 통합 백테스트 실행 중"); setBacktestControlState("RUNNING");\n                    toast("5분+15분 통합 백테스트를 시작했습니다.");\n                }).setNegativeButton("취소", null).show();\n    }\n\n'''
    text = text.replace(anchor, method + anchor, 1)
    main.write_text(text, encoding='utf-8')
